# Generated by Django 5.0 on 2024-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_no', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('start_point', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
